// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcXnmD_MVZ1vXEPM08mLfwH6J-asgQBmY',
    appId: '1:820950336707:web:2a1aab168919f57a0f0e76',
    messagingSenderId: '820950336707',
    projectId: 'bims-ac0f3',
    authDomain: 'bims-ac0f3.firebaseapp.com',
    storageBucket: 'bims-ac0f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhGrd_S8rKnyqpeUUCcRZXlsfzeaXSCts',
    appId: '1:820950336707:android:0df34b21d7922d710f0e76',
    messagingSenderId: '820950336707',
    projectId: 'bims-ac0f3',
    storageBucket: 'bims-ac0f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjiEz3lI56xlBQ4vo08BQLSa3lhuzm1p4',
    appId: '1:820950336707:ios:c58d5bf8933856860f0e76',
    messagingSenderId: '820950336707',
    projectId: 'bims-ac0f3',
    storageBucket: 'bims-ac0f3.appspot.com',
    iosClientId: '820950336707-jlvdur7jine0pqeovqh4gpknr959sdkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bims',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjiEz3lI56xlBQ4vo08BQLSa3lhuzm1p4',
    appId: '1:820950336707:ios:c58d5bf8933856860f0e76',
    messagingSenderId: '820950336707',
    projectId: 'bims-ac0f3',
    storageBucket: 'bims-ac0f3.appspot.com',
    iosClientId: '820950336707-jlvdur7jine0pqeovqh4gpknr959sdkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bims',
  );
}
